### ISSUE TITLE
w1_encode_done raised 8 cycles after computation start

### ISSUE THREAD

**Issue by cbatlubis** [chipsalliance/adams-bridge#41]
This report is just for documentation purpose as it was fixed in commit 2e468352ab3f9b846cf4332a7b19b20c2bdcbeb5

The module `decompose_w1_encode` initiate 8 rounds of keccak computations.
However, it's counter `rounds_count` decrements unconditionally each cycle, without waiting for the keccak computation to be finished, as indicated by an asserted `keccak_en`.
This causes the `encode_done` signal to be asserted just 8 cycles after the computation was started, i.e., too early.
We found that in a earlier design version, `keccak_en` was the condition for the counter to decrement.

We raised this issue in a meeting.
According to your finding this was an bug but it was unobservable at higher hierarchy levels and quickly fixed it in commit 2e468352ab3f9b846cf4332a7b19b20c2bdcbeb5

**Comment by mojtaba-bisheh** [comment]
fixed in https://github.com/chipsalliance/adams-bridge/pull/31
