### ISSUE TITLE
mldsa_ctrl just waits for PC incrementation

### ISSUE THREAD

**Issue by cbatlubis** [chipsalliance/adams-bridge#43]
This report is just for documentation purpose as it was already fixed.

In line 1421 in module `mldsa_ctrl` the generated signatures are checked and depending on this evaluation the program counter is incremented by either 1 (signature invalid) or 2 (signature valid).
When the generated signature is valid, then only the done signal, highlighting the completion of this process, needs to be asserted.
This is done when the program counter reaches the value of the local parameter `MLDSA_SIGN_GEN_E`.
`MLDSA_SIGN_GEN_E` is defined in module `mldsa_ctrl_pkg` line 440 as `MLDSA_SIGN_GEN_S + 9`.
We are wondering why the base value is incremented by 9 and not by 2.
From what we see in the waveform the design just waits the difference of clock cycles without doing anything.

So it was just a non-functional observation that does not affect the functionality of the design.

**Comment by mojtaba-bisheh** [comment]
fixed by https://github.com/chipsalliance/adams-bridge/pull/39
